; Script generated by Antigravity for Hungry Hub Admin Panel Setup
; Open this file in Inno Setup Compiler (free tool) to generate your final HungryHubAdminSetup.exe installer wizard.

[Setup]
AppId={{8F5B8B9B-7C6E-4BE3-B07B-231565C1AE5E}
AppName=Hungry Hub Admin Panel
AppVersion=1.0.0
AppPublisher=Hungry Hub
AppPublisherURL=https://www.thehungryhub.shop/
AppSupportURL=https://www.thehungryhub.shop/
AppUpdatesURL=https://www.thehungryhub.shop/
DefaultDirName={autopf}\HungryHubAdmin
DisableProgramGroupPage=yes
; Application icon for the installer file itself
SetupIconFile=HungryFastFoodAdmin\logo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
OutputDir=Output
OutputBaseFilename=HungryHubAdminSetup

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "HungryFastFoodAdmin\bin\Release\net10.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\Hungry Hub Admin Panel"; Filename: "{app}\HungryFastFoodAdmin.exe"; IconFilename: "{app}\logo.ico"
Name: "{autodesktop}\Hungry Hub Admin Panel"; Filename: "{app}\HungryFastFoodAdmin.exe"; IconFilename: "{app}\logo.ico"; Tasks: desktopicon

[Run]
Filename: "{app}\HungryFastFoodAdmin.exe"; Description: "{cm:LaunchProgram,Hungry Hub Admin Panel}"; Flags: nowait postinstall skipifsilent
